### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by moltar** [mafintosh/docker-browser-server#11]
Getting an error:

```
❯ docker-browser-server busybox --port 8080
~node_modules/root/index.js:30
Root.prototype.__proto__ = process.EventEmitter.prototype;
                                                ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (~node_modules/root/index.js:30:49)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (~node_modules/docker-browser-server/index.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
```

**Comment by moltar** [comment]
```
❯ node -v
v12.1.0
```

**Comment by james-milburn-crowe** [comment]
I have the same error. The software works on node v6.17.1 (npm v3.10.10), but stops working at v8 (after some trial and error).
