### ISSUE TITLE
Getting error in index.js file

### ISSUE THREAD

**Issue by shriya-mulay** [mafintosh/docker-browser-server#8]
I'm getting this error when I'm trying to launch container
$ docker-browser-server docker.io/httpd --port 8080
/usr/local/lib/node_modules/docker-browser-server/node_modules/root/index.js:30
Root.prototype.__proto__ = process.EventEmitter.prototype;
                                                ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/docker-browser-server/node_modules/root/index.js:30:49)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/docker-browser-server/index.js:8:12)
    at Module._compile (module.js:660:30)

**Comment by shriya-mulay** [comment]
I realized it was node.js version problem, i switched to version 7. It works fine now
